<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ProductAddRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|unique:products',
            'file'=>'required'
        ];
    }
    public function messages()
    {
        return [
            'name.required'=>'Tên không được để trống',
            'name.unique'=>"Tên $this->name đã tồn tại",
            'file.required'=>'Trường ảnh không được để trống'
        ]; // TODO: Change the autogenerated stub
    }
}
