<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
class ProductEditRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|unique:products,name,'.request()->id,
            // dd(request()->id)
            
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'Trường tên không được để trống',
            'name.unique' => "Tên $this->name đã tồn tại"
            

        ]; // TODO: Change the autogenerated stub

    }
}
